import { Item, User, Conversation, Story } from '@/types';

// ─── Mock Users ───────────────────────────────────────────────────────────────

export const MOCK_USERS: User[] = [
  {
    id: 'user1',
    username: 'berkeleybound',
    email: 'alex@berkeley.edu',
    avatar: 'https://i.pravatar.cc/150?u=user1abc',
    rating: 4.8,
    ratingCount: 24,
    itemsPosted: 12,
    itemsClaimed: 5,
    verified: true,
    verifiedEmail: true,
    trustScore: 92,
    bio: 'Grad student, passionate about zero waste 🌱',
    neighborhood: 'southside',
    joinedAt: new Date('2023-08-01'),
    environmentalImpactLbs: 340,
  },
  {
    id: 'user2',
    username: 'golden_bear_grace',
    email: 'grace@berkeley.edu',
    avatar: 'https://i.pravatar.cc/150?u=user2xyz',
    rating: 4.9,
    ratingCount: 51,
    itemsPosted: 24,
    itemsClaimed: 8,
    verified: true,
    verifiedEmail: true,
    trustScore: 97,
    bio: 'Moving out every year means free stuff for everyone 😄',
    neighborhood: 'northside',
    joinedAt: new Date('2023-01-15'),
    environmentalImpactLbs: 820,
  },
  {
    id: 'user3',
    username: 'telegraph_sam',
    email: 'sam@gmail.com',
    avatar: 'https://i.pravatar.cc/150?u=user3def',
    rating: 4.5,
    ratingCount: 12,
    itemsPosted: 6,
    itemsClaimed: 15,
    verified: false,
    verifiedEmail: false,
    trustScore: 68,
    bio: 'Love giving things new life',
    neighborhood: 'downtown',
    joinedAt: new Date('2024-02-10'),
    environmentalImpactLbs: 185,
  },
  {
    id: 'user4',
    username: 'elmwood_emma',
    email: 'emma@berkeley.edu',
    avatar: 'https://i.pravatar.cc/150?u=user4ghi',
    rating: 5.0,
    ratingCount: 8,
    itemsPosted: 8,
    itemsClaimed: 3,
    verified: true,
    verifiedEmail: true,
    trustScore: 88,
    bio: 'Minimalist. Sharing what I don\'t need ✨',
    neighborhood: 'elmwood',
    joinedAt: new Date('2024-09-01'),
    environmentalImpactLbs: 210,
  },
];

// ─── Mock Items ───────────────────────────────────────────────────────────────

export const MOCK_ITEMS: Item[] = [
  {
    id: 'item1',
    title: 'Blue IKEA Couch — Great Condition',
    description:
      'Moving out of my apartment and can\'t take this with me. Great shape, minimal wear. Perfect for a studio or living room. It\'s a 3-seater IKEA Ektorp. Pick up from curb Saturday morning.',
    category: 'furniture',
    tags: ['IKEA', 'large', 'like new', 'couch', '3-seater'],
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
      'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=800&q=80',
    ],
    latitude: 37.8673,
    longitude: -122.259,
    address: 'Telegraph Ave & Dwight Way',
    neighborhood: 'southside',
    status: 'available',
    userId: 'user1',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    viewCount: 47,
    interestedCount: 8,
    pickupMethod: 'curb',
    weightEstimateLbs: 80,
  },
  {
    id: 'item2',
    title: 'CS Textbooks — 61A, 61B, 170, 161',
    description:
      'CS 61A, 61B, CS 161, CS 170 textbooks plus a few math books. Save $200+! These are legitimately in great condition.',
    category: 'books',
    tags: ['CS', 'textbooks', 'berkeley', 'set', 'like new'],
    images: [
      'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=800&q=80',
    ],
    latitude: 37.8724,
    longitude: -122.2595,
    address: 'Near Sather Gate, Bancroft Way',
    neighborhood: 'southside',
    status: 'available',
    userId: 'user2',
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000),
    viewCount: 23,
    interestedCount: 5,
    pickupMethod: 'contact',
    weightEstimateLbs: 12,
  },
  {
    id: 'item3',
    title: 'Vintage Record Player + 30 Records',
    description:
      'Works great! Comes with about 30 records — classic rock, jazz, some folk. Moving and can\'t take everything.',
    category: 'electronics',
    tags: ['vintage', 'music', 'record player', 'works great', 'set'],
    images: [
      'https://images.unsplash.com/photo-1461784180009-21121b2f204c?w=800&q=80',
    ],
    latitude: 37.8686,
    longitude: -122.2705,
    address: 'Shattuck Ave, Near Cheeseboard',
    neighborhood: 'downtown',
    status: 'pending',
    userId: 'user3',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    viewCount: 89,
    interestedCount: 14,
    pickupMethod: 'scheduled',
    weightEstimateLbs: 8,
  },
  {
    id: 'item4',
    title: 'Monstera Plant — 4 Feet Tall',
    description:
      'Gorgeous monstera deliciosa, about 4 feet tall. Healthy and thriving. Must pick up — too heavy to transport. Comes with ceramic pot.',
    category: 'plants',
    tags: ['monstera', 'large', 'healthy', 'ceramic pot', 'indoor'],
    images: [
      'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=800&q=80',
    ],
    latitude: 37.8556,
    longitude: -122.2508,
    address: 'College Ave, Elmwood',
    neighborhood: 'elmwood',
    status: 'available',
    userId: 'user1',
    createdAt: new Date(Date.now() - 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 60 * 60 * 1000),
    viewCount: 34,
    interestedCount: 11,
    pickupMethod: 'curb',
    weightEstimateLbs: 15,
  },
  {
    id: 'item5',
    title: 'Standing Desk + Ergonomic Chair',
    description:
      'Full WFH setup — adjustable height standing desk and ergonomic office chair. Both in excellent condition. Perfect for a home office or study setup.',
    category: 'furniture',
    tags: ['standing desk', 'ergonomic', 'WFH', 'like new', 'set'],
    images: [
      'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80',
    ],
    latitude: 37.8885,
    longitude: -122.2703,
    address: 'Solano Ave, Albany/Berkeley',
    neighborhood: 'northside',
    status: 'available',
    userId: 'user2',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    viewCount: 61,
    interestedCount: 7,
    pickupMethod: 'curb',
    weightEstimateLbs: 65,
  },
  {
    id: 'item6',
    title: 'Vintage Leather Jacket — Size M',
    description:
      'Brown leather jacket, barely worn. Fit me perfectly but I\'m moving to Hawaii! Great for Berkeley winters.',
    category: 'clothing',
    tags: ['leather', 'vintage', 'size M', 'brown', 'like new'],
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=80',
    ],
    latitude: 37.871,
    longitude: -122.268,
    address: 'Downtown Berkeley',
    neighborhood: 'downtown',
    status: 'claimed',
    userId: 'user3',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    viewCount: 112,
    interestedCount: 22,
    pickupMethod: 'contact',
    weightEstimateLbs: 3,
  },
  {
    id: 'item7',
    title: 'KitchenAid Stand Mixer — Red',
    description:
      'Red KitchenAid 5qt stand mixer. Used maybe 10 times. All original attachments included (dough hook, whisk, paddle). It\'s heavy, arrange a time to pick up.',
    category: 'kitchen',
    tags: ['KitchenAid', 'like new', 'red', '5qt', 'all attachments'],
    images: [
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
    ],
    latitude: 37.864,
    longitude: -122.264,
    address: 'Benvenue Ave, Berkeley',
    neighborhood: 'southside',
    status: 'available',
    userId: 'user1',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    viewCount: 78,
    interestedCount: 16,
    pickupMethod: 'contact',
    weightEstimateLbs: 25,
  },
  {
    id: 'item8',
    title: 'Mountain Bike — Trek 820, 26"',
    description:
      'Trek 820 mountain bike. 21-speed, 26" wheels. Good condition, needs slight brake adjustment. I rode it for 2 years, barely on trails.',
    category: 'sports',
    tags: ['Trek', 'mountain bike', 'good condition', '26 inch', 'needs repair'],
    images: [
      'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&q=80',
    ],
    latitude: 37.876,
    longitude: -122.25,
    address: 'Panoramic Hill, Berkeley',
    neighborhood: 'north-hills',
    status: 'available',
    userId: 'user2',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    viewCount: 94,
    interestedCount: 18,
    pickupMethod: 'curb',
    weightEstimateLbs: 28,
  },
  {
    id: 'item9',
    title: 'IKEA Billy Bookcase — White',
    description:
      'Classic IKEA Billy bookcase. Disassembled and ready to go. All hardware included. 80cm wide, 202cm tall version.',
    category: 'furniture',
    tags: ['IKEA', 'Billy', 'white', 'bookcase', 'disassembled'],
    images: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
    ],
    latitude: 37.869,
    longitude: -122.294,
    address: '4th St, West Berkeley',
    neighborhood: 'west-berkeley',
    status: 'available',
    userId: 'user4',
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    viewCount: 29,
    interestedCount: 6,
    pickupMethod: 'curb',
    weightEstimateLbs: 35,
  },
  {
    id: 'item10',
    title: 'Cast Iron Skillet Set',
    description:
      'Lodge cast iron skillet set — 10" and 12" with a dutch oven. All pre-seasoned, in excellent condition.',
    category: 'kitchen',
    tags: ['Lodge', 'cast iron', 'set', 'like new', 'heavy'],
    images: [
      'https://images.unsplash.com/photo-1544816565-aa8c1166648f?w=800&q=80',
    ],
    latitude: 37.858,
    longitude: -122.252,
    address: 'Elmwood neighborhood',
    neighborhood: 'elmwood',
    status: 'available',
    userId: 'user4',
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 10 * 60 * 60 * 1000),
    viewCount: 44,
    interestedCount: 9,
    pickupMethod: 'scheduled',
    weightEstimateLbs: 20,
  },
];

// Add user data to items
MOCK_ITEMS.forEach((item) => {
  item.user = MOCK_USERS.find((u) => u.id === item.userId);
});

// ─── Mock Conversations ───────────────────────────────────────────────────────

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv1',
    itemId: 'item1',
    item: MOCK_ITEMS[0],
    participants: ['me', 'user1'],
    otherUser: MOCK_USERS[0],
    lastMessage: {
      id: 'msg1',
      conversationId: 'conv1',
      senderId: 'user1',
      text: 'Yes! It\'s still available. Come by Saturday morning.',
      createdAt: new Date(Date.now() - 15 * 60 * 1000),
      read: false,
    },
    unreadCount: 1,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'conv2',
    itemId: 'item4',
    item: MOCK_ITEMS[3],
    participants: ['me', 'user2'],
    otherUser: MOCK_USERS[1],
    lastMessage: {
      id: 'msg2',
      conversationId: 'conv2',
      senderId: 'me',
      text: 'I can pick up today around 3pm!',
      createdAt: new Date(Date.now() - 45 * 60 * 1000),
      read: true,
    },
    unreadCount: 0,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: 'conv3',
    itemId: 'item7',
    item: MOCK_ITEMS[6],
    participants: ['me', 'user1'],
    otherUser: MOCK_USERS[0],
    lastMessage: {
      id: 'msg3',
      conversationId: 'conv3',
      senderId: 'user1',
      text: 'Is this still available?',
      createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
      read: true,
    },
    unreadCount: 0,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
  },
];

// ─── Mock Stories ─────────────────────────────────────────────────────────────

export const MOCK_STORIES: Story[] = [
  {
    id: 'story1',
    userId: 'user2',
    user: MOCK_USERS[1],
    itemId: 'item5',
    item: MOCK_ITEMS[4],
    images: ['https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80'],
    caption: 'Scored this standing desk on Stooping! My WFH setup is finally complete 🙌',
    reactions: [
      { emoji: '❤️', count: 24 },
      { emoji: '🔥', count: 12 },
      { emoji: '🙌', count: 8 },
    ],
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    type: 'find',
  },
  {
    id: 'story2',
    userId: 'user4',
    user: MOCK_USERS[3],
    images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80'],
    caption: 'Before: ugly couch. After: painted & reupholstered! 🛋️✨ Thank you Berkeley Stooping!',
    reactions: [
      { emoji: '❤️', count: 47 },
      { emoji: '🔥', count: 31 },
      { emoji: '🙌', count: 19 },
    ],
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    type: 'transformation',
  },
  {
    id: 'story3',
    userId: 'user1',
    user: MOCK_USERS[0],
    images: ['https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=800&q=80'],
    caption: 'My living room after one month of Stooping. Nearly everything here was free 🌿',
    reactions: [
      { emoji: '❤️', count: 89 },
      { emoji: '🔥', count: 42 },
      { emoji: '🙌', count: 33 },
    ],
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    type: 'setup',
  },
];

// ─── Community Stats ──────────────────────────────────────────────────────────

export const COMMUNITY_STATS = {
  totalItems: 1847,
  totalWeightKeptFromLandfillLbs: 24350,
  activeUsersThisMonth: 412,
  itemsClaimedThisWeek: 89,
};
